[package]
name = "etheracts"
version = "0.1.0"
edition = "2024_07"

[lib]

[dependencies]
starknet = "2.12.2"
alexandria_bytes = "0.6.1"
openzeppelin_access = "2.0.0"
openzeppelin_account = "2.0.0"
openzeppelin_introspection = "2.0.0"
openzeppelin_token = "2.0.0"
openzeppelin_upgrades = "2.0.0"

[dev-dependencies]
snforge_std = "0.50.0"
assert_macros = "2.12.2"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
