[package]
name = "etheracts"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.13.1"
license = "MIT"
description = "High resolution renders and an arbitrary registration protocol."
authors = ["NovemberFork", "0xDegenDeveloper"]
readme = "README.md"
homepage = "https://etheracts.novemberfork.io/"
repository = "https://github.com/NovemberFork/etheracts"


[lib]

[dependencies]
starknet = "2.13.1"
alexandria_bytes = "0.6.1"
openzeppelin_access = "2.0.0"
openzeppelin_account = "2.0.0"
openzeppelin_introspection = "2.0.0"
openzeppelin_token = "2.0.0"
openzeppelin_upgrades = "2.0.0"

[dev-dependencies]
snforge_std = "0.52.0"
assert_macros = "2.13.1"

[[target.starknet-contract]]
sierra = true
casm = true

[cairo]
sierra-replace-ids = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
